version: '3.8'

services:
  app:
    build: .
    container_name: taskmaster-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmasterdb
      SPRING_DATASOURCE_USERNAME: taskmaster
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskmaster-db
    environment:
      POSTGRES_DB: taskmasterdb
      POSTGRES_USER: taskmaster
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
